#!/bin/bash

regex='^[0-9]+([.][0-9]+)?$'
sum=0
[[ -p /dev/stdin ]] && { mapfile -t; set -- "${MAPFILE[@]}"; set -- $@; }

for var in "$@" 
do
    if [[ $var =~ $regex ]]; then
        sum=`echo $sum + $var | bc`
    fi
done

echo $sum
