@ECHO OFF

KodPowrotu\KodPowrotu\KodPowrotu.exe %* /s

IF %ERRORLEVEL% LEQ 10 (
	ECHO PRZEKAZANO: %ERRORLEVEL%
)

IF %ERRORLEVEL% EQU 11 (
	ECHO BRAK PARAMETROW
)

IF %ERRORLEVEL% EQU 12 (
	ECHO PARAMETR $1 NIE JEST CYFRA
) 

IF %ERRORLEVEL% EQU 13 (
	ECHO NIEWLASCIWA WARTOSC PARAMETRU %1
) 

 IF %ERRORLEVEL% GEQ 14 (
	ECHO PRZEKAZANO: %ERRORLEVEL%
)
