# Generated by Django 3.1.3 on 2020-11-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesRecord',
        ),
    ]
