# Generated by Django 3.1.3 on 2020-11-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapi', '0002_delete_salesrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrecord',
            options={'managed': False},
        ),
    ]
