# Generated by Django 3.1.3 on 2020-11-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapi', '0003_auto_20201127_1719'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currencyrecord',
            table='UsdToPln',
        ),
    ]
