# Generated by Django 3.1.3 on 2020-12-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapi', '0005_dailysales_salesorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRecordInter',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('effectivedate', models.TextField(blank=True, db_column='EffectiveDate', null=True)),
                ('currencyvalue', models.FloatField(blank=True, db_column='CurrencyValue', null=True)),
                ('interpolated', models.IntegerField(blank=True, db_column='Interpolated', null=True)),
            ],
            options={
                'db_table': 'UsdToPlnInter',
                'managed': False,
            },
        ),
    ]
