# Generated by Django 3.1.3 on 2020-12-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapi', '0006_currencyrecordinter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRecordInter',
        ),
        migrations.AlterModelTable(
            name='currencyrecord',
            table='UsdToPlnInter',
        ),
    ]
