# Generated by Django 3.1.4 on 2020-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStats',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('sales_sum', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=3)),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('interpolated', models.BooleanField(default='False')),
            ],
            options={
                'ordering': ('date',),
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
